package com.zuicoding.platform.demo.domain;

public class PostsWithBLOBs extends Posts {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column posts.markdown
     *
     * @mbggenerated Wed May 24 15:41:58 CST 2017
     */
    private String markdown;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column posts.html
     *
     * @mbggenerated Wed May 24 15:41:58 CST 2017
     */
    private String html;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column posts.image
     *
     * @mbggenerated Wed May 24 15:41:58 CST 2017
     */
    private String image;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column posts.markdown
     *
     * @return the value of posts.markdown
     *
     * @mbggenerated Wed May 24 15:41:58 CST 2017
     */
    public String getMarkdown() {
        return markdown;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column posts.markdown
     *
     * @param markdown the value for posts.markdown
     *
     * @mbggenerated Wed May 24 15:41:58 CST 2017
     */
    public void setMarkdown(String markdown) {
        this.markdown = markdown == null ? null : markdown.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column posts.html
     *
     * @return the value of posts.html
     *
     * @mbggenerated Wed May 24 15:41:58 CST 2017
     */
    public String getHtml() {
        return html;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column posts.html
     *
     * @param html the value for posts.html
     *
     * @mbggenerated Wed May 24 15:41:58 CST 2017
     */
    public void setHtml(String html) {
        this.html = html == null ? null : html.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column posts.image
     *
     * @return the value of posts.image
     *
     * @mbggenerated Wed May 24 15:41:58 CST 2017
     */
    public String getImage() {
        return image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column posts.image
     *
     * @param image the value for posts.image
     *
     * @mbggenerated Wed May 24 15:41:58 CST 2017
     */
    public void setImage(String image) {
        this.image = image == null ? null : image.trim();
    }
}