package com.zuicoding.platform.demo.domain;

import java.util.Date;

public class Posts {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column posts.id
     *
     * @mbggenerated Wed May 24 15:41:58 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column posts.uuid
     *
     * @mbggenerated Wed May 24 15:41:58 CST 2017
     */
    private String uuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column posts.title
     *
     * @mbggenerated Wed May 24 15:41:58 CST 2017
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column posts.slug
     *
     * @mbggenerated Wed May 24 15:41:58 CST 2017
     */
    private String slug;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column posts.featured
     *
     * @mbggenerated Wed May 24 15:41:58 CST 2017
     */
    private Boolean featured;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column posts.page
     *
     * @mbggenerated Wed May 24 15:41:58 CST 2017
     */
    private Boolean page;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column posts.status
     *
     * @mbggenerated Wed May 24 15:41:58 CST 2017
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column posts.language
     *
     * @mbggenerated Wed May 24 15:41:58 CST 2017
     */
    private String language;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column posts.meta_title
     *
     * @mbggenerated Wed May 24 15:41:58 CST 2017
     */
    private String metaTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column posts.meta_description
     *
     * @mbggenerated Wed May 24 15:41:58 CST 2017
     */
    private String metaDescription;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column posts.author_id
     *
     * @mbggenerated Wed May 24 15:41:58 CST 2017
     */
    private Integer authorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column posts.created_at
     *
     * @mbggenerated Wed May 24 15:41:58 CST 2017
     */
    private Date createdAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column posts.created_by
     *
     * @mbggenerated Wed May 24 15:41:58 CST 2017
     */
    private Integer createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column posts.updated_at
     *
     * @mbggenerated Wed May 24 15:41:58 CST 2017
     */
    private Date updatedAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column posts.updated_by
     *
     * @mbggenerated Wed May 24 15:41:58 CST 2017
     */
    private Integer updatedBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column posts.published_at
     *
     * @mbggenerated Wed May 24 15:41:58 CST 2017
     */
    private Date publishedAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column posts.published_by
     *
     * @mbggenerated Wed May 24 15:41:58 CST 2017
     */
    private Integer publishedBy;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column posts.id
     *
     * @return the value of posts.id
     *
     * @mbggenerated Wed May 24 15:41:58 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column posts.id
     *
     * @param id the value for posts.id
     *
     * @mbggenerated Wed May 24 15:41:58 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column posts.uuid
     *
     * @return the value of posts.uuid
     *
     * @mbggenerated Wed May 24 15:41:58 CST 2017
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column posts.uuid
     *
     * @param uuid the value for posts.uuid
     *
     * @mbggenerated Wed May 24 15:41:58 CST 2017
     */
    public void setUuid(String uuid) {
        this.uuid = uuid == null ? null : uuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column posts.title
     *
     * @return the value of posts.title
     *
     * @mbggenerated Wed May 24 15:41:58 CST 2017
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column posts.title
     *
     * @param title the value for posts.title
     *
     * @mbggenerated Wed May 24 15:41:58 CST 2017
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column posts.slug
     *
     * @return the value of posts.slug
     *
     * @mbggenerated Wed May 24 15:41:58 CST 2017
     */
    public String getSlug() {
        return slug;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column posts.slug
     *
     * @param slug the value for posts.slug
     *
     * @mbggenerated Wed May 24 15:41:58 CST 2017
     */
    public void setSlug(String slug) {
        this.slug = slug == null ? null : slug.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column posts.featured
     *
     * @return the value of posts.featured
     *
     * @mbggenerated Wed May 24 15:41:58 CST 2017
     */
    public Boolean getFeatured() {
        return featured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column posts.featured
     *
     * @param featured the value for posts.featured
     *
     * @mbggenerated Wed May 24 15:41:58 CST 2017
     */
    public void setFeatured(Boolean featured) {
        this.featured = featured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column posts.page
     *
     * @return the value of posts.page
     *
     * @mbggenerated Wed May 24 15:41:58 CST 2017
     */
    public Boolean getPage() {
        return page;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column posts.page
     *
     * @param page the value for posts.page
     *
     * @mbggenerated Wed May 24 15:41:58 CST 2017
     */
    public void setPage(Boolean page) {
        this.page = page;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column posts.status
     *
     * @return the value of posts.status
     *
     * @mbggenerated Wed May 24 15:41:58 CST 2017
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column posts.status
     *
     * @param status the value for posts.status
     *
     * @mbggenerated Wed May 24 15:41:58 CST 2017
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column posts.language
     *
     * @return the value of posts.language
     *
     * @mbggenerated Wed May 24 15:41:58 CST 2017
     */
    public String getLanguage() {
        return language;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column posts.language
     *
     * @param language the value for posts.language
     *
     * @mbggenerated Wed May 24 15:41:58 CST 2017
     */
    public void setLanguage(String language) {
        this.language = language == null ? null : language.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column posts.meta_title
     *
     * @return the value of posts.meta_title
     *
     * @mbggenerated Wed May 24 15:41:58 CST 2017
     */
    public String getMetaTitle() {
        return metaTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column posts.meta_title
     *
     * @param metaTitle the value for posts.meta_title
     *
     * @mbggenerated Wed May 24 15:41:58 CST 2017
     */
    public void setMetaTitle(String metaTitle) {
        this.metaTitle = metaTitle == null ? null : metaTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column posts.meta_description
     *
     * @return the value of posts.meta_description
     *
     * @mbggenerated Wed May 24 15:41:58 CST 2017
     */
    public String getMetaDescription() {
        return metaDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column posts.meta_description
     *
     * @param metaDescription the value for posts.meta_description
     *
     * @mbggenerated Wed May 24 15:41:58 CST 2017
     */
    public void setMetaDescription(String metaDescription) {
        this.metaDescription = metaDescription == null ? null : metaDescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column posts.author_id
     *
     * @return the value of posts.author_id
     *
     * @mbggenerated Wed May 24 15:41:58 CST 2017
     */
    public Integer getAuthorId() {
        return authorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column posts.author_id
     *
     * @param authorId the value for posts.author_id
     *
     * @mbggenerated Wed May 24 15:41:58 CST 2017
     */
    public void setAuthorId(Integer authorId) {
        this.authorId = authorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column posts.created_at
     *
     * @return the value of posts.created_at
     *
     * @mbggenerated Wed May 24 15:41:58 CST 2017
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column posts.created_at
     *
     * @param createdAt the value for posts.created_at
     *
     * @mbggenerated Wed May 24 15:41:58 CST 2017
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column posts.created_by
     *
     * @return the value of posts.created_by
     *
     * @mbggenerated Wed May 24 15:41:58 CST 2017
     */
    public Integer getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column posts.created_by
     *
     * @param createdBy the value for posts.created_by
     *
     * @mbggenerated Wed May 24 15:41:58 CST 2017
     */
    public void setCreatedBy(Integer createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column posts.updated_at
     *
     * @return the value of posts.updated_at
     *
     * @mbggenerated Wed May 24 15:41:58 CST 2017
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column posts.updated_at
     *
     * @param updatedAt the value for posts.updated_at
     *
     * @mbggenerated Wed May 24 15:41:58 CST 2017
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column posts.updated_by
     *
     * @return the value of posts.updated_by
     *
     * @mbggenerated Wed May 24 15:41:58 CST 2017
     */
    public Integer getUpdatedBy() {
        return updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column posts.updated_by
     *
     * @param updatedBy the value for posts.updated_by
     *
     * @mbggenerated Wed May 24 15:41:58 CST 2017
     */
    public void setUpdatedBy(Integer updatedBy) {
        this.updatedBy = updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column posts.published_at
     *
     * @return the value of posts.published_at
     *
     * @mbggenerated Wed May 24 15:41:58 CST 2017
     */
    public Date getPublishedAt() {
        return publishedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column posts.published_at
     *
     * @param publishedAt the value for posts.published_at
     *
     * @mbggenerated Wed May 24 15:41:58 CST 2017
     */
    public void setPublishedAt(Date publishedAt) {
        this.publishedAt = publishedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column posts.published_by
     *
     * @return the value of posts.published_by
     *
     * @mbggenerated Wed May 24 15:41:58 CST 2017
     */
    public Integer getPublishedBy() {
        return publishedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column posts.published_by
     *
     * @param publishedBy the value for posts.published_by
     *
     * @mbggenerated Wed May 24 15:41:58 CST 2017
     */
    public void setPublishedBy(Integer publishedBy) {
        this.publishedBy = publishedBy;
    }
}