package com.zuicoding.platform.demo.dao;

import com.zuicoding.platform.demo.domain.Posts;
import com.zuicoding.platform.demo.domain.PostsWithBLOBs;

public interface PostsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posts
     *
     * @mbggenerated Wed May 24 15:41:58 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posts
     *
     * @mbggenerated Wed May 24 15:41:58 CST 2017
     */
    int insert(PostsWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posts
     *
     * @mbggenerated Wed May 24 15:41:58 CST 2017
     */
    int insertSelective(PostsWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posts
     *
     * @mbggenerated Wed May 24 15:41:58 CST 2017
     */
    PostsWithBLOBs selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posts
     *
     * @mbggenerated Wed May 24 15:41:58 CST 2017
     */
    int updateByPrimaryKeySelective(PostsWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posts
     *
     * @mbggenerated Wed May 24 15:41:58 CST 2017
     */
    int updateByPrimaryKeyWithBLOBs(PostsWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posts
     *
     * @mbggenerated Wed May 24 15:41:58 CST 2017
     */
    int updateByPrimaryKey(Posts record);
}